### ISSUE TITLE
No shadows, ambient occlusion or any post processing effects

### ISSUE THREAD

**Issue by FixPlsShinoow** [Lila0110/kuno#4]
I am using windows 10 with Amd rx 5700 xt and r 5 3600 cpu.

When I followed the instructions and installed, game launches but there is no shadows and any other post processing.
I tried all the other configs in the rar, no luck.

Also what do I do with the data folder in the kuno-main rar? It never specified in the instructions.
Anyway, can you please tell me what is causing this and how to fix it? Vulkan is super beneficial for my GPU.

**Comment by Empelton** [comment]
The data folder is just for a pre-existing archive in DW_DLC39. And I don't know necessarily too much about how this works but I do have shadows and AO with PPFX on my R5 3600 CPU and GTX 1080. I am not too qualified to fully answer this for you though.

**Comment by Lila0110** [comment]
Hello, thank you for reaching out.

Currently Kuno is using the highest level optimizations without any balance for graphical fidelity. This means until there is a stable set of releases, there will not be any options to for varying optimization levels, but only one with heavily reduced graphics. However Kuno does not remove PPFX, or anything like that. 

But it *does* remove shadows. If you wish I can send you a modified build that has shadows.

> Also what do I do with the data folder in the kuno-main rar? It never specified in the instructions.

The `/game/data/` directory in the main repository is a non-compressed version of the kuno source. It is not meant to be used, unless you want to compress it yourself.

*For further help, feel free to contact me on [Discord](https://discord.gg/Tk7R2VVQ36).*

**Comment by Lila0110** [comment]
Will have a stable release up within a couple days. Closing issue.
