### ISSUE TITLE
Question, can Reshade work with Kuno?

### ISSUE THREAD

**Issue by Blackgrowl** [Lila0110/kuno#5]
Hey there.

I was wondering if it's possible to use Reshade with Kuno itself?
From what I remember, DXVK had issues with Reshade before, but now it's completely stable and has little to no performance issues.
I've tried simply installing Reshade as Vulkan but it didn't work.

**Comment by Empelton** [comment]
I would ask you to attempt to install it using DX as the render engine and seeing if it works or not.

**Comment by Lila0110** [comment]
*Apologies for the late response.*

# Answer
> Hey there.
> I was wondering if it's possible to use **Reshade** with **Kuno** itself?

Yes it may not be as optimal as **`DXVK`** with **Kuno**, but it **should** work.

> From what I remember, **`DXVK`** had issues with **Reshade** before, but now it's completely stable and has little to no performance issues.
> I've tried simply installing **Reshade** as **Vulkan** but it didn't work.

Sadly I and anyone else  (*[@Empelton](https://www.github.com/Empelton)*) failed to get **Reshade** working with **Dying Light** using **`DXVK`** on **Windows**.

Currently it seems **`DXVK`** + **Reshade** is a **Linux** only thing for **Dying Light**. *Untested but I plan to soon.*

# To address this
`1`. I will find out if **Reshade** works on **Proton/SteamPlay (*Linux*)**.

`2`. I will add documentation to the [`README.md`](https://github.com/Lila0110/kuno#readme) stating the current status of **Reshade** + **`DXVK`** on both platforms.

# Additionally
Feel free to add me on **[Discord](https://discord.gg/qA9c5dXT)** at `Lilan#2644` if you wish to further discuss this privately.

**Comment by Blackgrowl** [comment]
Sorry, I should have mentioned that I use Windows 10, so I guess I might as well consider not using Reshade altogether or wait out for you to figure out if there is a way.
I'll add you on Discord, maybe you can give me prototype versions of Kuno.

**Comment by Lila0110** [comment]
As it turns out **Reshade** does indeed work fine with **Linux** using **Proton/SteamPlay**. Installation was about the same and it works without issue. Maybe someday we can get **Reshade** working on **Windows**. For now it will remain **Linux** only sorry.
